name: lab02
on: push
jobs:
  test:
      runs-on: ubuntu-latest
      steps:
         - run: echo "Hello Lab02!"
         - run: pip install nbconvert
         - run: python -m nbconvert --to html lab02/lab02.ipynb
