name: lab5

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Update & install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --fix-missing pandoc inkscape texlive-xetex

      - name: Install Python packages
        run: pip install pint nbconvert latex ipykernel matplotlib scipy numpy

      - name: Run notebook and convert to PDF
        run: |
          jupyter nbconvert --to pdf --execute ./lab_05/lab05_assignment.ipynb \
            --output assignment.pdf

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: lab5-report
          path: lab_05/lab05_assignment.pdf
