name: lab6

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update & install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --fix-missing pandoc inkscape texlive-xetex

      - name: Install Python packages
        run: |
          pip install --upgrade pip
          pip install \
            numpy scipy matplotlib \
            ipykernel nbconvert \
            pint \
            open-atmos-jupyter-utils  \
            nbqa pylint

      - name: Convert Notebook to PDF
        run: |
          jupyter nbconvert --to pdf --execute ./lab_06/lab06_assignment.ipynb \
            --output lab06_assignment.pdf

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: lab6-report
          path: lab_06/lab06_assignment.pdf
